FILE_CONTENTS=$(sed '/#PLUGINSTART/,/#PLUGINEND/d' ./install.sh)

NEW_HEADER="#PLUGINSTART
# this section is automatically generated by build_installer.sh
# please do not modify!
files=(
"

for file in $(find ./plugin); do
  if [ "$file" == "./plugin" ]; then continue; fi
  if [ -d "$file" ]; then continue; fi
  NEW_HEADER="$NEW_HEADER  ${file#./plugin/}
"
done

NEW_HEADER="$NEW_HEADER)
#PLUGINEND
"

echo "$NEW_HEADER$FILE_CONTENTS" >|./install.sh
